(function () {
  const encoder = new TextEncoder(); let crcTable;
  function makeCrcTable(){const table=new Uint32Array(256);for(let n=0;n<256;n++){let c=n;for(let k=0;k<8;k++)c=c&1?0xedb88320^(c>>>1):c>>>1;table[n]=c>>>0;}return table;}
  function crc32(bytes){crcTable=crcTable||makeCrcTable();let c=0xffffffff;for(const b of bytes)c=crcTable[(c^b)&0xff]^(c>>>8);return(c^0xffffffff)>>>0;}
  function dosDateTime(date=new Date()){return{time:(date.getHours()<<11)|(date.getMinutes()<<5)|Math.floor(date.getSeconds()/2),day:((date.getFullYear()-1980)<<9)|((date.getMonth()+1)<<5)|date.getDate()};}
  function u32(view,offset,value){view.setUint32(offset,value>>>0,true)} function u16(view,offset,value){view.setUint16(offset,value&0xffff,true)}
  function concat(parts){const total=parts.reduce((sum,part)=>sum+part.length,0);const out=new Uint8Array(total);let offset=0;for(const part of parts){out.set(part,offset);offset+=part.length;}return out;}
  function createZip(files){const localParts=[],centralParts=[];let offset=0;const now=dosDateTime();for(const file of files){const nameBytes=encoder.encode(file.path.replace(/^\/+/,''));const data=file.bytes instanceof Uint8Array?file.bytes:encoder.encode(file.content||'');const crc=crc32(data);const local=new Uint8Array(30+nameBytes.length);const lv=new DataView(local.buffer);u32(lv,0,0x04034b50);u16(lv,4,20);u16(lv,6,0);u16(lv,8,0);u16(lv,10,now.time);u16(lv,12,now.day);u32(lv,14,crc);u32(lv,18,data.length);u32(lv,22,data.length);u16(lv,26,nameBytes.length);local.set(nameBytes,30);localParts.push(local,data);const central=new Uint8Array(46+nameBytes.length);const cv=new DataView(central.buffer);u32(cv,0,0x02014b50);u16(cv,4,20);u16(cv,6,20);u16(cv,8,0);u16(cv,10,0);u16(cv,12,now.time);u16(cv,14,now.day);u32(cv,16,crc);u32(cv,20,data.length);u32(cv,24,data.length);u16(cv,28,nameBytes.length);u32(cv,42,offset);central.set(nameBytes,46);centralParts.push(central);offset+=local.length+data.length;}const centralSize=centralParts.reduce((sum,part)=>sum+part.length,0);const end=new Uint8Array(22);const ev=new DataView(end.buffer);u32(ev,0,0x06054b50);u16(ev,8,files.length);u16(ev,10,files.length);u32(ev,12,centralSize);u32(ev,16,offset);return new Blob([concat([...localParts,...centralParts,end])],{type:'application/zip'});}
  function downloadBlob(blob,filename){const url=URL.createObjectURL(blob);const link=document.createElement('a');link.href=url;link.download=filename;link.style.display='none';document.body.appendChild(link);link.click();link.remove();setTimeout(()=>URL.revokeObjectURL(url),500);}
  window.GuidebookZip = { createZip, downloadBlob };
}());
